name: Run Benchmark
on: workflow_dispatch
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: executables
          path: build
      - name: Run benchmark script
        run: |
          chmod +x build/*
          cp build/* ./
          ./benchmark.sh
        shell: bash
