name: Build and Run Benchmark
on: workflow_dispatch
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build source
        run: make release
      - name: Run benchmark
        run: |
          ./benchmark.sh | tee results.csv
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark
          path: results.csv
