name: Build and Run Benchmark
on: workflow_dispatch
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build source
        run: make release
      - name: Run benchmark script
        run: ./benchmark.sh
        shell: bash
